### ISSUE TITLE
As a developer, I need to resize the graphics size

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#220]
Where: In the search tool (tested), probably also in the Inspect and Compare tools

Issue: the legend in Y axis gets hidden by the switch button when the graphic is not high enough (see word "recor":
![screen shot 2018-11-30 at 15 55 36](https://user-images.githubusercontent.com/8133228/49296395-675b5a00-f4b8-11e8-87cd-b0dc1d649615.png)

**Comment by avlisodraude** [comment]
**@lilimelgar @jblom :**

Issue solve in branch (labo-components)
bug/#220-graphics-not-resizing-properly

**What's been done?**
Setting a min-height for the Responsivecontainer and  repositioning the label to the bottom using property position="insideBottomLeft" 
As for recharts in http://recharts.org/en-US/api/Label 

**Where:** 
In graph for single search and comparison recipe.
 
It should now work as in screencast:
https://drive.google.com/open?id=1YncR5ZIFgqvCAS9Qkm5GrQhfibhl9a5r

I created a pull request to solve this bug.

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I've tested this and it looked good. I merged it with master.

**Comment by lilimelgar** [comment]
@avlisodraude Tested in Master, all OK for Search tool and Inspect tool, but the bug is not yet fixed in the Compare tool.

**Comment by lilimelgar** [comment]
@avlisodraude: Tested in Master branch (since branch _"#260"_ was already merged). I also tested in branch #166. The graphic seems to be OK when resizing, but you mentioned you had moved the label "number of records" to the bottom left, please check before sending pull request.

**Comment by lilimelgar** [comment]
@avlisodraude I see this solved in branch 166, ready to be merged!
