### ISSUE TITLE
As a user I want the menu displayed properly

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#293]
**As a user I want the menu displayed properly.**

**Category:**
Bug.
**Where?**
clariah-mediasuite project

**How to reproduce:**
In the menu while resizing the screen the Learn dropdown menu does go outside the screen view and a gap between the header menu and the dropdown appears as shown in:
![issue-bug-293.jpg](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/aae8e6b7-6a16-45c9-98d5-84205360eee6)

**Screencast example:**
https://drive.google.com/open?id=1VJHgku_qxjtzdOcIc9uFF0FKLYVUJS4Z

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :

**Issue reported by @lilimelgar on 18-02-2019** 
It's been solved in clariah-mediasuite project branch:
issue/#293-bug-when-resizing-screen-in-dropdown-menu

**Github branch at:**
https://github.com/beeldengeluid/clariah-mediasuite/tree/issue/%23293-bug-when-resizing-screen-in-dropdown-menu

@lilimelgar :
Please test in clariah-mediasuite :
git pull
git checkout issue/#293-bug-when-resizing-screen-in-dropdown-menu
npm run prod

run with console open and make sure the cache is been cleared.

**Comment by lilimelgar** [comment]
@avlisodraude I tested in:
-clariah-mediasuite/src 
-branch: issue/#293-bug-when-resizing-screen-in-dropdown-menu
-npm run prod
-cleared cached
the issue still persists: see [screencast](https://drive.google.com/drive/folders/0B8StOK8IHMiQX0F1akJhLUV2akE)

**Comment by avlisodraude** [comment]
**@lilimelgar:**
I checked the issue and I'm pretty sure it's a CACHE issue. 
Please make sure that after switching branch and running _'npm run prod'_ the CACHE in your browser is cleared (with the console tool open).
In the next screencast you can see the differences between Master and the corresponding branch.

**Screencast:**
 https://drive.google.com/open?id=1t5j_RVT82nUGT8BZFWanYNc6b3QMfIBb

**Comment by lilimelgar** [comment]
@avlisodraude: Tested in the branch above, ready for pull request

**Comment by jblom** [comment]
@lilimelgar @avlisodraude merged, but found two more styling things for the menu. Will report them now
