### ISSUE TITLE
bug: in case of no results because of the date filter: show only one error message (related to the date range)

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#335]
Show the top message only

![Schermafbeelding 2019-03-25 om 13.41.48 (2).png](https://images.zenhubusercontent.com/5a127cc38a75884b90880fdc/2cfff370-7685-4dc6-a1ae-2ac05987a4d6)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Issue for labo-components project done in branch:
_issue/#335-show-only-one-error-msg_

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I fixed this in the master, I think :-P

**Comment by lilimelgar** [comment]
@jblom I tested in production, unluckily I still see the two messages:

<img width="1273" alt="Screenshot 2019-05-02 at 15 39 38" src="https://user-images.githubusercontent.com/8133228/57079430-9b011100-6cf0-11e9-9076-4e0742751cc0.png">

**Comment by jblom** [comment]
@lilimelgar ok I put this back into the backlog
