### ISSUE TITLE
As a developer, I need to fix a styling issue in the Facet selector

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#380]
Where: Search tool, Facet selector
Issue: when the facet term is too long, the text goes over the number and moves the number of the second row to the left (Image)
Examples: OH collection, creator facet

![Screenshot 2019-05-02 at 10.16.38.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/5f4548ca-f7f2-4ded-b5a1-b1c1f18b4fdf)

**Comment by avlisodraude** [comment]
**@lilimelgar @jblom** 

Issue for labo-components project done in branch:
issue/#380-fix-styling-in-facets

Pull request created
https://github.com/beeldengeluid/labo-components/pull/397


### What's been done?
For label longer than the available space and SASS Mixin has been created/used so if this issue appears the text is shorten to the available space as shown in the next screenshots.
This issue was present in the selected facets too. There the mixin has also been used.

### Screenshots
**Issue for selected items**
![Screenshot 2019-05-16 at 13.42.06.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/737fac2a-6acc-4de5-b315-f40a2debf1b7)

**After applying the mixin**
![Screenshot 2019-05-16 at 14.00.53.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/56f72bfc-f0c8-4147-9a6d-ced873523c4f)
---
**Issue for list items**
![Screenshot 2019-05-16 at 14.03.36.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/0dc4cde7-e058-4ce5-a129-794cf399ef50)
**After applying the mixin**
![Screenshot 2019-05-16 at 13.36.51.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/f9a6e0df-09f7-414f-80c6-a153af9fe4a9)

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I fixed this using native css ellipsis. It should be ok now, but did not test fully yet. It's in the master. Will close this, but added the "help wanted" label, so that Liliana can test whenever she has a computer to test on

**Comment by avlisodraude** [comment]
@jblom 
@lilimelgar Tested this issue on master and the issue remains (see screenshots)
![Screenshot 2019-05-29 at 13.57.22.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/f752f3a3-5a4b-4684-be21-2520ad3d4f86)
![Screenshot 2019-05-29 at 13.52.49.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/0aac2dc1-62db-481d-a14b-c88dd790f7eb)

**Comment by avlisodraude** [comment]
@jblom @lilimelgar 
(Updated issue)

### Motivation: 
Issue done after @lilimelgar ' test

### Done:

- Fix issue in search box when resizing facets (**screenshot 1**)
- Add ellipses to facet items (**screenshot 2**)
- Add ellipses to 'selected facet items' (**screenshot 3**)
- Fix issue in facets extra options when resizing (**screenshot 4**) which addresses issues with labeling texts
  - Change label text from REMOVE FACET to Remove
  - Remove uppercase to labels (more consistent with block headers and btn options stylings)
- Add title attribute to headers (so the user will see the full name when hovering in case the ellipse cuts the text) (**screenshot 5**)

### Screenshots
**screenshot 1**
![Screenshot 2019-06-06 at 13.28.17.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/cac836aa-1fc3-4ef9-a671-8f6212009124)

**screenshot 2**
![Screenshot 2019-06-06 at 13.32.12.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/ec089c0b-a2ba-42cf-b694-bb699fdda488)

**screenshot 3**
![Screenshot 2019-06-06 at 13.37.41.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/56109a1d-7464-45d5-98c1-9f6a39306935)

**screenshot 4**
![Screenshot 2019-06-06 at 13.40.14.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/3b20caf1-457c-4b56-8742-8a59a0eea376)

**screenshot 5**
![Screenshot 2019-06-06 at 13.53.38.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/517d5a34-af34-48e2-bd45-9868bbd53e62)

**Comment by jwassenaarbg** [comment]
Looks good to me. Functionally works and changes look logical.

**Comment by jblom** [comment]
@avlisodraude @jwassenaarbg looks good. However reverted the BUTTONS to uppercase text again, since that's consistent with the rest (e.g. the workspace), part of FW's design and I think that it helps in distinguishing between information (normal casing) and buttons.

**Comment by jblom** [comment]
@lilimelgar this one is now also deployed on test, so you can test it too. Please remove the **help wanted** label when you're done & it's all good
